version: "3.8"

services:
  # documenttemplateswebapp:
  #   build: .
  #   volumes:
  #     - ./Data:/app/Data
  #   depends_on:
  #     - mongodb_logs
  #   restart: unless-stopped
  #   ports:
  #     - 8080:80
    
  mongodb_logs:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - ./Docker/Volumes:/data/db
    restart: unless-stopped
    ports:
      - 27017:27017